const festivalData = {
    1: {
        1: { "Festival": "New Year", "Event": "Global Family Day", "National Holiday": true },
        2: { "Festival": "None", "Event": "First US air mail service inaugurated (1918)", "National Holiday": false },
        3: { "Festival": "None", "Event": "J.R.R. Tolkien's Birthday", "National Holiday": false },
        4: { "Festival": "None", "Event": "World Braille Day", "National Holiday": false },
        5: { "Festival": "None", "Event": "Discovery of dwarf planet Ceres (1801)", "National Holiday": false },
        6: { "Festival": "None", "Event": "First telegraph line completed in USA (1838)", "National Holiday": false },
        7: { "Festival": "None", "Event": "Galileo discovers Jupiter’s moons (1610)", "National Holiday": false },
        8: { "Festival": "None", "Event": "Stephen Hawking (1942) born", "National Holiday": false },
        9: { "Festival": "None", "Event": "Apple’s first iPhone announcement (2007)", "National Holiday": false },
        10: { "Festival": "None", "Event": "League of Nations founded (1920) | World Hindi Day", "National Holiday": false },
        11: { "Festival": "None", "Event": "First use of insulin to treat diabetes (1922)", "National Holiday": false },
        12: { "Festival": "None", "Event": "Swami Vivekananda's Birthday (1863)", "National Holiday": false },
        13: { "Festival": "None", "Event": "Murder of Emile Zola (1906)", "National Holiday": false },
        14: { "Festival": "Bhogi", "Event": "First demonstration of X-rays (1896)", "National Holiday": true },
        15: { "Festival": "Pongal / Makar Sankranti", "Event": "Wikipedia Day", "National Holiday": true },
        16: { "Festival": "None", "Event": "First meeting of League of Nations (1920)", "National Holiday": false },
        17: { "Festival": "None", "Event": "Birthday of Benjamin Franklin (1706)", "National Holiday": false },
        18: { "Festival": "None", "Event": "Thesaurus Day", "National Holiday": false },
        19: { "Festival": "None", "Event": "First atomic submarine launched (1955)", "National Holiday": false },
        20: { "Festival": "None", "Event": "Barack Obama inaugurated (2009)", "National Holiday": false },
        21: { "Festival": "None", "Event": "First Concorde flight (1976)", "National Holiday": false },
        22: { "Festival": "None", "Event": "Queen Victoria’s death (1901)", "National Holiday": false },
        23: { "Festival": "None", "Event": "Birthday of Subhas Chandra Bose (1897)", "National Holiday": false },
        24: { "Festival": "None", "Event": "International Day of Education", "National Holiday": false },
        25: { "Festival": "None", "Event": "National Voters Day (India)", "National Holiday": false },
        26: { "Festival": "Republic Day (India)", "Event": "India becomes a Republic (1950)", "National Holiday": true },
        27: { "Festival": "None", "Event": "International Holocaust Remembrance Day", "National Holiday": false },
        28: { "Festival": "None", "Event": "Thaipusam", "National Holiday": false },
        29: { "Festival": "None", "Event": "National Puzzle Day", "National Holiday": false },
        30: { "Festival": "None", "Event": "Martyrs' Day", "National Holiday": false },
        31: { "Festival": "None", "Event": "13th Amendment abolishing slavery passed (1865)", "National Holiday": false }
    },
    2: {
        1: { "Festival": "None", "Event": "National Freedom Day (US)", "National Holiday": false },
        2: { "Festival": "None", "Event": "World Wetlands Day", "National Holiday": false },
        3: { "Festival": "None", "Event": "The Day the Music Died (1959)", "National Holiday": false },
        4: { "Festival": "None", "Event": "World Cancer Day", "National Holiday": false },
        5: { "Festival": "None", "Event": "Western Zodiac New Moon (varies)", "National Holiday": false },
        6: { "Festival": "None", "Event": "New Zealand Waitangi Day", "National Holiday": false },
        7: { "Festival": "None", "Event": "Charles Dickens' Birthday (1812)", "National Holiday": false },
        8: { "Festival": "None", "Event": "Boy Scouts of America founded (1910)", "National Holiday": false },
        9: { "Festival": "None", "Event": "National Pizza Day (US)", "National Holiday": false },
        10: { "Festival": "None", "Event": "India’s first postage stamp issued (1854)", "National Holiday": false },
        11: { "Festival": "None", "Event": "International Day of Women and Girls in Science", "National Holiday": false },
        12: { "Festival": "None", "Event": "Darwin Day (Charles Darwin's Birthday, 1809)", "National Holiday": false },
        13: { "Festival": "None", "Event": "World Radio Day", "National Holiday": false },
        14: { "Festival": "None", "Event": "Valentine's Day", "National Holiday": false },
        15: { "Festival": "None", "Event": "Galileo's Birthday (1564)", "National Holiday": false },
        16: { "Festival": "None", "Event": "Lithuanian Independence Day", "National Holiday": false },
        17: { "Festival": "None", "Event": "Random Acts of Kindness Day", "National Holiday": false },
        18: { "Festival": "None", "Event": "Pluto discovered (1930)", "National Holiday": false },
        19: { "Festival": "None", "Event": "Shivaji Jayanti (Birth of Chhatrapati Shivaji Maharaj)", "National Holiday": false },
        20: { "Festival": "None", "Event": "World Day of Social Justice", "National Holiday": false },
        21: { "Festival": "Maha Shivaratri (Varies)", "Event": "International Mother Language Day", "National Holiday": true },
        22: { "Festival": "None", "Event": "World Thinking Day", "National Holiday": false },
        23: { "Festival": "None", "Event": "US Marines raise flag at Iwo Jima (1945)", "National Holiday": false },
        24: { "Festival": "None", "Event": "Steve Jobs' Birthday (1955)", "National Holiday": false },
        25: { "Festival": "None", "Event": "First powered flight in India (1911)", "National Holiday": false },
        26: { "Festival": "None", "Event": "Levi Strauss born (1829)", "National Holiday": false },
        27: { "Festival": "None", "Event": "International Polar Bear Day", "National Holiday": false },
        28: { "Festival": "None", "Event": "National Science Day (India, Raman Effect 1928)", "National Holiday": false },
        29: { "Festival": "None", "Event": "Leap Year Day (every 4 years)", "National Holiday": false }
    },
    3: {
        1: { "Festival": "None", "Event": "Zero Discrimination Day", "National Holiday": false },
        2: { "Festival": "None", "Event": "Read Across America Day (US)", "National Holiday": false },
        3: { "Festival": "None", "Event": "World Wildlife Day", "National Holiday": false },
        4: { "Festival": "None", "Event": "National Safety Day (India)", "National Holiday": false },
        5: { "Festival": "None", "Event": "International Day for Disarmament and Non-Proliferation Awareness", "National Holiday": false },
        6: { "Festival": "None", "Event": "European Day of the Righteous", "National Holiday": false },
        7: { "Festival": "None", "Event": "Janaki Jayanti (varies)", "National Holiday": false },
        8: { "Festival": "None", "Event": "International Women’s Day", "National Holiday": false },
        9: { "Festival": "None", "Event": "Barbie Day (US)", "National Holiday": false },
        10: { "Festival": "None", "Event": "CISF Raising Day (India)", "National Holiday": false },
        11: { "Festival": "None", "Event": "World Plumbing Day", "National Holiday": false },
        12: { "Festival": "None", "Event": "Mauritius Independence Day", "National Holiday": false },
        13: { "Festival": "None", "Event": "No Smoking Day (Second Wednesday)", "National Holiday": false },
        14: { "Festival": "None", "Event": "Pi Day / International Day of Mathematics", "National Holiday": false },
        15: { "Festival": "None", "Event": "World Consumer Rights Day", "National Holiday": false },
        16: { "Festival": "None", "Event": "National Vaccination Day (India)", "National Holiday": false },
        17: { "Festival": "None", "Event": "St. Patrick's Day", "National Holiday": false },
        18: { "Festival": "None", "Event": "Ordnance Factories Day (India)", "National Holiday": false },
        19: { "Festival": "None", "Event": "World Sleep Day (varies)", "National Holiday": false },
        20: { "Festival": "None", "Event": "International Day of Happiness", "National Holiday": false },
        21: { "Festival": "Holi (Varies)", "Event": "World Forestry Day", "National Holiday": true },
        22: { "Festival": "None", "Event": "World Water Day", "National Holiday": false },
        23: { "Festival": "None", "Event": "Shaheed Diwas (India)", "National Holiday": false },
        24: { "Festival": "None", "Event": "World Tuberculosis (TB) Day", "National Holiday": false },
        25: { "Festival": "Good Friday (varies)", "Event": "None", "National Holiday": true },
        26: { "Festival": "None", "Event": "Bangladesh Independence Day", "National Holiday": false },
        27: { "Festival": "None", "Event": "World Theatre Day", "National Holiday": false },
        28: { "Festival": "None", "Event": "Earth Hour (last Saturday)", "National Holiday": false },
        29: { "Festival": "None", "Event": "National Vietnam War Veterans Day (US)", "National Holiday": false },
        30: { "Festival": "None", "Event": "Doctors’ Day (US)", "National Holiday": false },
        31: { "Festival": "None", "Event": "International Transgender Day of Visibility", "National Holiday": false }
    },
    4: {
        1: { "Festival": "None", "Event": "April Fools' Day", "National Holiday": false },
        2: { "Festival": "Ram Navami (Varies)", "Event": "World Autism Awareness Day", "National Holiday": false },
        3: { "Festival": "None", "Event": "Find a Rainbow Day", "National Holiday": false },
        4: { "Festival": "None", "Event": "International Day for Mine Awareness", "National Holiday": false },
        5: { "Festival": "None", "Event": "National Maritime Day (India)", "National Holiday": false },
        6: { "Festival": "None", "Event": "International Day of Sport for Development and Peace", "National Holiday": false },
        7: { "Festival": "None", "Event": "World Health Day", "National Holiday": false },
        8: { "Festival": "None", "Event": "International Romani Day", "National Holiday": false },
        9: { "Festival": "Ugadi / Gudi Padwa (Varies)", "Event": "Jallianwala Bagh Massacre Day (India)", "National Holiday": true },
        10: { "Festival": "None", "Event": "Siblings Day", "National Holiday": false },
        11: { "Festival": "None", "Event": "National Safe Motherhood Day (India)", "National Holiday": false },
        12: { "Festival": "None", "Event": "International Day of Human Space Flight", "National Holiday": false },
        13: { "Festival": "None", "Event": "Jallianwala Bagh Massacre Day Observance", "National Holiday": false },
        14: { "Festival": "Ambedkar Jayanti", "Event": "Baisakhi / Vishu / Tamil Puthandu (Varies)", "National Holiday": true },
        15: { "Festival": "Pohela Boishakh (Bengali New Year)", "Event": "World Art Day", "National Holiday": true },
        16: { "Festival": "Hanuman Jayanti (Varies)", "Event": "Save the Elephant Day", "National Holiday": true },
        17: { "Festival": "None", "Event": "World Haemophilia Day", "National Holiday": false },
        18: { "Festival": "None", "Event": "World Heritage Day", "National Holiday": false },
        19: { "Festival": "None", "Event": "None", "National Holiday": false },
        20: { "Festival": "None", "Event": "UN Chinese Language Day", "National Holiday": false },
        21: { "Festival": "None", "Event": "National Civil Services Day (India)", "National Holiday": false },
        22: { "Festival": "None", "Event": "Earth Day", "National Holiday": false },
        23: { "Festival": "None", "Event": "World Book and Copyright Day", "National Holiday": false },
        24: { "Festival": "None", "Event": "National Panchayati Raj Day (India)", "National Holiday": false },
        25: { "Festival": "None", "Event": "World Malaria Day", "National Holiday": false },
        26: { "Festival": "None", "Event": "World Intellectual Property Day", "National Holiday": false },
        27: { "Festival": "None", "Event": "Freedom Day (South Africa)", "National Holiday": false },
        28: { "Festival": "None", "Event": "World Day for Safety and Health at Work", "National Holiday": false },
        29: { "Festival": "None", "Event": "International Dance Day", "National Holiday": false },
        30: { "Festival": "None", "Event": "Ayushman Bharat Diwas (India)", "National Holiday": false }
    },
    5: {
        1: { "Festival": "May Day (International Workers' Day)", "Event": "Maharashtra Day, Gujarat Day", "National Holiday": true },
        2: { "Festival": "None", "Event": "World Tuna Day", "National Holiday": false },
        3: { "Festival": "None", "Event": "World Press Freedom Day", "National Holiday": false },
        4: { "Festival": "None", "Event": "International Firefighters’ Day", "National Holiday": false },
        5: { "Festival": "None", "Event": "World Asthma Day (1st Tuesday of May)", "National Holiday": false },
        6: { "Festival": "None", "Event": "None", "National Holiday": false },
        7: { "Festival": "None", "Event": "World Athletics Day", "National Holiday": false },
        8: { "Festival": "None", "Event": "World Red Cross Day", "National Holiday": false },
        9: { "Festival": "None", "Event": "Rabindranath Tagore Jayanti (Varies)", "National Holiday": true },
        10: { "Festival": "None", "Event": "Mother's Day (2nd Sunday of May)", "National Holiday": false },
        11: { "Festival": "None", "Event": "National Technology Day (India)", "National Holiday": false },
        12: { "Festival": "None", "Event": "International Nurses Day", "National Holiday": false },
        13: { "Festival": "None", "Event": "None", "National Holiday": false },
        14: { "Festival": "None", "Event": "None", "National Holiday": false },
        15: { "Festival": "None", "Event": "International Day of Families", "National Holiday": false },
        16: { "Festival": "Buddha Purnima (Varies)", "Event": "None", "National Holiday": true },
        17: { "Festival": "None", "Event": "World Telecommunication Day", "National Holiday": false },
        18: { "Festival": "None", "Event": "International Museum Day", "National Holiday": false },
        19: { "Festival": "None", "Event": "None", "National Holiday": false },
        20: { "Festival": "None", "Event": "World Bee Day", "National Holiday": false },
        21: { "Festival": "None", "Event": "Anti-Terrorism Day (India)", "National Holiday": false },
        22: { "Festival": "None", "Event": "International Day for Biological Diversity", "National Holiday": false },
        23: { "Festival": "None", "Event": "World Turtle Day", "National Holiday": false },
        24: { "Festival": "None", "Event": "Commonwealth Day (India, Varies)", "National Holiday": false },
        25: { "Festival": "None", "Event": "African Liberation Day", "National Holiday": false },
        26: { "Festival": "None", "Event": "None", "National Holiday": false },
        27: { "Festival": "None", "Event": "None", "National Holiday": false },
        28: { "Festival": "None", "Event": "Menstrual Hygiene Day", "National Holiday": false },
        29: { "Festival": "None", "Event": "International Day of UN Peacekeepers", "National Holiday": false },
        30: { "Festival": "None", "Event": "Goa Statehood Day", "National Holiday": true },
        31: { "Festival": "None", "Event": "World No Tobacco Day", "National Holiday": false }
    },
    6: {
        1: { "Festival": "None", "Event": "Global Parents’ Day", "National Holiday": false },
        2: { "Festival": "None", "Event": "None", "National Holiday": false },
        3: { "Festival": "None", "Event": "World Bicycle Day", "National Holiday": false },
        4: { "Festival": "None", "Event": "International Day of Innocent Children Victims of Aggression", "National Holiday": false },
        5: { "Festival": "None", "Event": "World Environment Day", "National Holiday": false },
        6: { "Festival": "None", "Event": "D-Day", "National Holiday": false },
        7: { "Festival": "None", "Event": "None", "National Holiday": false },
        8: { "Festival": "None", "Event": "World Oceans Day", "National Holiday": false },
        9: { "Festival": "None", "Event": "None", "National Holiday": false },
        10: { "Festival": "None", "Event": "None", "National Holiday": false },
        11: { "Festival": "None", "Event": "World Gin Day (2nd Saturday of June)", "National Holiday": false },
        12: { "Festival": "None", "Event": "None", "National Holiday": false },
        13: { "Festival": "None", "Event": "International Albinism Awareness Day", "National Holiday": false },
        14: { "Festival": "None", "Event": "Flag Day (USA)", "National Holiday": false },
        15: { "Festival": "None", "Event": "Father's Day (3rd Sunday of June)", "National Holiday": false },
        16: { "Festival": "None", "Event": "None", "National Holiday": false },
        17: { "Festival": "None", "Event": "World Day to Combat Desertification and Drought", "National Holiday": false },
        18: { "Festival": "None", "Event": "None", "National Holiday": false },
        19: { "Festival": "None", "Event": "Juneteenth (USA)", "National Holiday": false },
        20: { "Festival": "None", "Event": "World Refugee Day", "National Holiday": false },
        21: { "Festival": "International Yoga Day", "Event": "Summer Solstice", "National Holiday": false },
        22: { "Festival": "None", "Event": "None", "National Holiday": false },
        23: { "Festival": "None", "Event": "None", "National Holiday": false },
        24: { "Festival": "None", "Event": "None", "National Holiday": false },
        25: { "Festival": "None", "Event": "None", "National Holiday": false },
        26: { "Festival": "None", "Event": "International Day Against Drug Abuse and Illicit Trafficking", "National Holiday": false },
        27: { "Festival": "None", "Event": "Micro-, Small and Medium-sized Enterprises Day", "National Holiday": false },
        28: { "Festival": "None", "Event": "None", "National Holiday": false },
        29: { "Festival": "None", "Event": "None", "National Holiday": false },
        30: { "Festival": "None", "Event": "Social Media Day", "National Holiday": false }
    },
    7: {
        1: { "Festival": "None", "Event": "None", "National Holiday": false },
        2: { "Festival": "None", "Event": "World UFO Day", "National Holiday": false },
        3: { "Festival": "None", "Event": "None", "National Holiday": false },
        4: { "Festival": "None", "Event": "Independence Day (USA)", "National Holiday": true },
        5: { "Festival": "None", "Event": "None", "National Holiday": false },
        6: { "Festival": "None", "Event": "None", "National Holiday": false },
        7: { "Festival": "None", "Event": "None", "National Holiday": false },
        8: { "Festival": "None", "Event": "None", "National Holiday": false },
        9: { "Festival": "None", "Event": "None", "National Holiday": false },
        10: { "Festival": "None", "Event": "None", "National Holiday": false },
        11: { "Festival": "None", "Event": "World Population Day", "National Holiday": false },
        12: { "Festival": "None", "Event": "None", "National Holiday": false },
        13: { "Festival": "None", "Event": "None", "National Holiday": false },
        14: { "Festival": "None", "Event": "Bastille Day (France)", "National Holiday": true },
        15: { "Festival": "None", "Event": "None", "National Holiday": false },
        16: { "Festival": "None", "Event": "None", "National Holiday": false },
        17: { "Festival": "None", "Event": "None", "National Holiday": false },
        18: { "Festival": "None", "Event": "Nelson Mandela International Day", "National Holiday": false },
        19: { "Festival": "None", "Event": "None", "National Holiday": false },
        20: { "Festival": "None", "Event": "Moon Day (50th Anniversary of Apollo 11 landing)", "National Holiday": false },
        21: { "Festival": "None", "Event": "None", "National Holiday": false },
        22: { "Festival": "None", "Event": "None", "National Holiday": false },
        23: { "Festival": "None", "Event": "None", "National Holiday": false },
        24: { "Festival": "None", "Event": "None", "National Holiday": false },
        25: { "Festival": "None", "Event": "None", "National Holiday": false },
        26: { "Festival": "None", "Event": "None", "National Holiday": false },
        27: { "Festival": "None", "Event": "None", "National Holiday": false },
        28: { "Festival": "None", "Event": "None", "National Holiday": false },
        29: { "Festival": "None", "Event": "None", "National Holiday": false },
        30: { "Festival": "None", "Event": "None", "National Holiday": false },
        31: { "Festival": "None", "Event": "None", "National Holiday": false }
    },
    8: {
        1: { "Festival": "None", "Event": "None", "National Holiday": false },
        2: { "Festival": "None", "Event": "None", "National Holiday": false },
        3: { "Festival": "None", "Event": "None", "National Holiday": false },
        4: { "Festival": "None", "Event": "None", "National Holiday": false },
        5: { "Festival": "None", "Event": "None", "National Holiday": false },
        6: { "Festival": "None", "Event": "None", "National Holiday": false },
        7: { "Festival": "None", "Event": "None", "National Holiday": false },
        8: { "Festival": "None", "Event": "None", "National Holiday": false },
        9: { "Festival": "None", "Event": "None", "National Holiday": false },
        10: { "Festival": "None", "Event": "None", "National Holiday": false },
        11: { "Festival": "None", "Event": "None", "National Holiday": false },
        12: { "Festival": "None", "Event": "None", "National Holiday": false },
        13: { "Festival": "None", "Event": "None", "National Holiday": false },
        14: { "Festival": "None", "Event": "None", "National Holiday": false },
        15: { "Festival": "Independence Day (India)", "Event": "None", "National Holiday": true },
        16: { "Festival": "None", "Event": "None", "National Holiday": false },
        17: { "Festival": "None", "Event": "None", "National Holiday": false },
        18: { "Festival": "None", "Event": "None", "National Holiday": false },
        19: { "Festival": "None", "Event": "World Humanitarian Day", "National Holiday": false },
        20: { "Festival": "None", "Event": "None", "National Holiday": false },
        21: { "Festival": "None", "Event": "None", "National Holiday": false },
        22: { "Festival": "None", "Event": "None", "National Holiday": false },
        23: { "Festival": "None", "Event": "None", "National Holiday": false },
        24: { "Festival": "None", "Event": "None", "National Holiday": false },
        25: { "Festival": "None", "Event": "None", "National Holiday": false },
        26: { "Festival": "None", "Event": "Women's Equality Day (USA)", "National Holiday": false },
        27: { "Festival": "None", "Event": "None", "National Holiday": false },
        28: { "Festival": "None", "Event": "None", "National Holiday": false },
        29: { "Festival": "None", "Event": "None", "National Holiday": false },
        30: { "Festival": "None", "Event": "None", "National Holiday": false },
        31: { "Festival": "None", "Event": "None", "National Holiday": false }
    },
    9: {
        1: { "Festival": "None", "Event": "Labor Day (USA)", "National Holiday": true },
        2: { "Festival": "None", "Event": "None", "National Holiday": false },
        3: { "Festival": "None", "Event": "None", "National Holiday": false },
        4: { "Festival": "None", "Event": "None", "National Holiday": false },
        5: { "Festival": "Teacher's Day (India)", "Event": "None", "National Holiday": true },
        6: { "Festival": "None", "Event": "None", "National Holiday": false },
        7: { "Festival": "None", "Event": "None", "National Holiday": false },
        8: { "Festival": "None", "Event": "None", "National Holiday": false },
        9: { "Festival": "None", "Event": "None", "National Holiday": false },
        10: { "Festival": "None", "Event": "None", "National Holiday": false },
        11: { "Festival": "None", "Event": "None", "National Holiday": false },
        12: { "Festival": "None", "Event": "None", "National Holiday": false },
        13: { "Festival": "None", "Event": "None", "National Holiday": false },
        14: { "Festival": "None", "Event": "None", "National Holiday": false },
        15: { "Festival": "None", "Event": "None", "National Holiday": false },
        16: { "Festival": "None", "Event": "None", "National Holiday": false },
        17: { "Festival": "None", "Event": "None", "National Holiday": false },
        18: { "Festival": "None", "Event": "None", "National Holiday": false },
        19: { "Festival": "None", "Event": "None", "National Holiday": false },
        20: { "Festival": "None", "Event": "None", "National Holiday": false },
        21: { "Festival": "None", "Event": "International Day of Peace", "National Holiday": false },
        22: { "Festival": "None", "Event": "None", "National Holiday": false },
        23: { "Festival": "None", "Event": "None", "National Holiday": false },
        24: { "Festival": "None", "Event": "None", "National Holiday": false },
        25: { "Festival": "None", "Event": "None", "National Holiday": false },
        26: { "Festival": "None", "Event": "None", "National Holiday": false },
        27: { "Festival": "None", "Event": "None", "National Holiday": false },
        28: { "Festival": "None", "Event": "None", "National Holiday": false },
        29: { "Festival": "None", "Event": "None", "National Holiday": false },
        30: { "Festival": "None", "Event": "None", "National Holiday": false }
    },
    10: {
        1: { "Festival": "None", "Event": "None", "National Holiday": false },
        2: { "Festival": "Gandhi Jayanti (India)", "Event": "None", "National Holiday": true },
        3: { "Festival": "None", "Event": "None", "National Holiday": false },
        4: { "Festival": "None", "Event": "None", "National Holiday": false },
        5: { "Festival": "None", "Event": "None", "National Holiday": false },
        6: { "Festival": "None", "Event": "None", "National Holiday": false },
        7: { "Festival": "None", "Event": "None", "National Holiday": false },
        8: { "Festival": "None", "Event": "None", "National Holiday": false },
        9: { "Festival": "None", "Event": "None", "National Holiday": false },
        10: { "Festival": "None", "Event": "None", "National Holiday": false },
        11: { "Festival": "None", "Event": "None", "National Holiday": false },
        12: { "Festival": "None", "Event": "None", "National Holiday": false },
        13: { "Festival": "None", "Event": "None", "National Holiday": false },
        14: { "Festival": "None", "Event": "None", "National Holiday": false },
        15: { "Festival": "None", "Event": "None", "National Holiday": false },
        16: { "Festival": "None", "Event": "None", "National Holiday": false },
        17: { "Festival": "None", "Event": "None", "National Holiday": false },
        18: { "Festival": "None", "Event": "None", "National Holiday": false },
        19: { "Festival": "None", "Event": "None", "National Holiday": false },
        20: { "Festival": "None", "Event": "None", "National Holiday": false },
        21: { "Festival": "None", "Event": "None", "National Holiday": false },
        22: { "Festival": "None", "Event": "None", "National Holiday": false },
        23: { "Festival": "None", "Event": "None", "National Holiday": false },
        24: { "Festival": "None", "Event": "None", "National Holiday": false },
        25: { "Festival": "None", "Event": "None", "National Holiday": false },
        26: { "Festival": "None", "Event": "None", "National Holiday": false },
        27: { "Festival": "None", "Event": "None", "National Holiday": false },
        28: { "Festival": "None", "Event": "None", "National Holiday": false },
        29: { "Festival": "None", "Event": "None", "National Holiday": false },
        30: { "Festival": "None", "Event": "None", "National Holiday": false },
        31: { "Festival": "Halloween", "Event": "None", "National Holiday": false }
    },
    11: {
        1: { "Festival": "All Saints' Day", "Event": "None", "National Holiday": false },
        2: { "Festival": "All Souls' Day", "Event": "None", "National Holiday": false },
        3: { "Festival": "None", "Event": "None", "National Holiday": false },
        4: { "Festival": "None", "Event": "None", "National Holiday": false },
        5: { "Festival": "None", "Event": "None", "National Holiday": false },
        6: { "Festival": "None", "Event": "None", "National Holiday": false },
        7: { "Festival": "None", "Event": "None", "National Holiday": false },
        8: { "Festival": "None", "Event": "None", "National Holiday": false },
        9: { "Festival": "None", "Event": "None", "National Holiday": false },
        10: { "Festival": "None", "Event": "None", "National Holiday": false },
        11: { "Festival": "Veterans Day (USA)", "Event": "None", "National Holiday": true },
        12: { "Festival": "None", "Event": "None", "National Holiday": false },
        13: { "Festival": "None", "Event": "None", "National Holiday": false },
        14: { "Festival": "Children's Day (India)", "Event": "None", "National Holiday": true },
        15: { "Festival": "None", "Event": "None", "National Holiday": false },
        16: { "Festival": "None", "Event": "None", "National Holiday": false },
        17: { "Festival": "None", "Event": "None", "National Holiday": false },
        18: { "Festival": "None", "Event": "None", "National Holiday": false },
        19: { "Festival": "None", "Event": "None", "National Holiday": false },
        20: { "Festival": "None", "Event": "None", "National Holiday": false },
        21: { "Festival": "None", "Event": "None", "National Holiday": false },
        22: { "Festival": "None", "Event": "None", "National Holiday": false },
        23: { "Festival": "None", "Event": "None", "National Holiday": false },
        24: { "Festival": "None", "Event": "None", "National Holiday": false },
        25: { "Festival": "None", "Event": "None", "National Holiday": false },
        26: { "Festival": "None", "Event": "None", "National Holiday": false },
        27: { "Festival": "Thanksgiving (USA)", "Event": "None", "National Holiday": true },
        28: { "Festival": "None", "Event": "None", "National Holiday": false },
        29: { "Festival": "None", "Event": "None", "National Holiday": false },
        30: { "Festival": "None", "Event": "None", "National Holiday": false }
    },
    12: {
        1: { "Festival": "World AIDS Day", "Event": "None", "National Holiday": false },
        2: { "Festival": "None", "Event": "None", "National Holiday": false },
        3: { "Festival": "International Day of Persons with Disabilities", "Event": "None", "National Holiday": false },
        4: { "Festival": "None", "Event": "None", "National Holiday": false },
        5: { "Festival": "None", "Event": "None", "National Holiday": false },
        6: { "Festival": "St. Nicholas Day", "Event": "None", "National Holiday": false },
        7: { "Festival": "None", "Event": "None", "National Holiday": false },
        8: { "Festival": "Immaculate Conception", "Event": "None", "National Holiday": true },
        9: { "Festival": "None", "Event": "None", "National Holiday": false },
        10: { "Festival": "Human Rights Day", "Event": "None", "National Holiday": false },
        11: { "Festival": "None", "Event": "None", "National Holiday": false },
        12: { "Festival": "None", "Event": "None", "National Holiday": false },
        13: { "Festival": "St. Lucia's Day", "Event": "None", "National Holiday": false },
        14: { "Festival": "None", "Event": "None", "National Holiday": false },
        15: { "Festival": "None", "Event": "None", "National Holiday": false },
        16: { "Festival": "None", "Event": "None", "National Holiday": false },
        17: { "Festival": "None", "Event": "None", "National Holiday": false },
        18: { "Festival": "None", "Event": "None", "National Holiday": false },
        19: { "Festival": "None", "Event": "None", "National Holiday": false },
        20: { "Festival": "None", "Event": "None", "National Holiday": false },
        21: { "Festival": "Winter Solstice", "Event": "None", "National Holiday": false },
        22: { "Festival": "None", "Event": "None", "National Holiday": false },
        23: { "Festival": "None", "Event": "None", "National Holiday": false },
        24: { "Festival": "Christmas Eve", "Event": "None", "National Holiday": false },
        25: { "Festival": "Christmas Day", "Event": "None", "National Holiday": true },
        26: { "Festival": "Boxing Day", "Event": "None", "National Holiday": true },
        27: { "Festival": "None", "Event": "None", "National Holiday": false },
        28: { "Festival": "None", "Event": "None", "National Holiday": false },
        29: { "Festival": "None", "Event": "None", "National Holiday": false },
        30: { "Festival": "None", "Event": "None", "National Holiday": false },
        31: { "Festival": "New Year's Eve", "Event": "None", "National Holiday": false }
    }
};
